"""empty message

Revision ID: ecbec554bca6
Revises: 
Create Date: 2021-04-21 04:15:02.452095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecbec554bca6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('packet',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('af_packet',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ifname', sa.String(length=50), nullable=False),
    sa.Column('proto', sa.Integer(), nullable=False),
    sa.Column('pkttype', sa.String(length=25), nullable=False),
    sa.Column('hatype', sa.Integer(), nullable=False),
    sa.Column('hwaddr', sa.String(length=50), nullable=False),
    sa.Column('packet_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['packet_id'], ['packet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('arp',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('HTYPE', sa.Integer(), nullable=False),
    sa.Column('PTYPE', sa.Integer(), nullable=False),
    sa.Column('HLEN', sa.Integer(), nullable=False),
    sa.Column('PLEN', sa.Integer(), nullable=False),
    sa.Column('operation', sa.Integer(), nullable=False),
    sa.Column('SHA', sa.String(length=30), nullable=False),
    sa.Column('SPA', sa.String(length=30), nullable=False),
    sa.Column('THA', sa.String(length=30), nullable=False),
    sa.Column('TPA', sa.String(length=30), nullable=False),
    sa.Column('packet_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['packet_id'], ['packet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cdp',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('packet_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['packet_id'], ['packet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('icmp',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type_', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('packet_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['packet_id'], ['packet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('icmpv6',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type_', sa.Integer(), nullable=False),
    sa.Column('code', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('packet_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['packet_id'], ['packet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('igmp',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('type_', sa.Integer(), nullable=False),
    sa.Column('max_resp_time', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.Integer(), nullable=False),
    sa.Column('group_address', sa.String(length=40), nullable=False),
    sa.Column('packet_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['packet_id'], ['packet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipv4',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('IHL', sa.Integer(), nullable=False),
    sa.Column('DSCP', sa.Integer(), nullable=False),
    sa.Column('ECN', sa.Integer(), nullable=False),
    sa.Column('total_length', sa.Integer(), nullable=False),
    sa.Column('identification', sa.BigInteger(), nullable=False),
    sa.Column('flags', sa.Integer(), nullable=False),
    sa.Column('fragment_offset', sa.Integer(), nullable=False),
    sa.Column('TTL', sa.Integer(), nullable=False),
    sa.Column('header_checksum', sa.Integer(), nullable=False),
    sa.Column('source_address', sa.String(length=40), nullable=False),
    sa.Column('destination_address', sa.String(length=40), nullable=False),
    sa.Column('options', sa.Text(), nullable=False),
    sa.Column('packet_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['packet_id'], ['packet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipv6',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('DS', sa.Integer(), nullable=False),
    sa.Column('ECN', sa.Integer(), nullable=False),
    sa.Column('flow_label', sa.BigInteger(), nullable=False),
    sa.Column('payload_length', sa.Integer(), nullable=False),
    sa.Column('next_header', sa.Integer(), nullable=False),
    sa.Column('hop_limit', sa.Integer(), nullable=False),
    sa.Column('source_address', sa.String(length=70), nullable=False),
    sa.Column('destination_address', sa.String(length=70), nullable=False),
    sa.Column('ext_headers', sa.Text(), nullable=False),
    sa.Column('packet_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['packet_id'], ['packet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lldp',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('typelengthvalue', sa.Text(), nullable=False),
    sa.Column('packet_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['packet_id'], ['packet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lsap_one',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('packet_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['packet_id'], ['packet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packet_802_2',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('DSAP', sa.String(length=50), nullable=False),
    sa.Column('SSAP', sa.String(length=50), nullable=False),
    sa.Column('control', sa.String(length=50), nullable=False),
    sa.Column('packet_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['packet_id'], ['packet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('packet_802_3',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('destination_MAC', sa.String(length=50), nullable=False),
    sa.Column('source_MAC', sa.String(length=50), nullable=False),
    sa.Column('ethertype', sa.Integer(), nullable=False),
    sa.Column('packet_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['packet_id'], ['packet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('snap_ext',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('OUI', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('packet_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['packet_id'], ['packet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tcp',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_port', sa.Integer(), nullable=False),
    sa.Column('destination_port', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.BigInteger(), nullable=False),
    sa.Column('acknowledgment_number', sa.BigInteger(), nullable=False),
    sa.Column('data_offset', sa.Integer(), nullable=False),
    sa.Column('reserved', sa.Integer(), nullable=False),
    sa.Column('flags', sa.Text(), nullable=False),
    sa.Column('window_size', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.Integer(), nullable=False),
    sa.Column('urgent_pointer', sa.Integer(), nullable=False),
    sa.Column('options', sa.Text(), nullable=False),
    sa.Column('packet_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['packet_id'], ['packet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('udp',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source_port', sa.Integer(), nullable=False),
    sa.Column('destination_port', sa.Integer(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('checksum', sa.Integer(), nullable=False),
    sa.Column('packet_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['packet_id'], ['packet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('unknown',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('identifier', sa.Integer(), nullable=False),
    sa.Column('packet_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['packet_id'], ['packet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('unknown')
    op.drop_table('udp')
    op.drop_table('tcp')
    op.drop_table('snap_ext')
    op.drop_table('packet_802_3')
    op.drop_table('packet_802_2')
    op.drop_table('lsap_one')
    op.drop_table('lldp')
    op.drop_table('ipv6')
    op.drop_table('ipv4')
    op.drop_table('igmp')
    op.drop_table('icmpv6')
    op.drop_table('icmp')
    op.drop_table('cdp')
    op.drop_table('arp')
    op.drop_table('af_packet')
    op.drop_table('packet')
    # ### end Alembic commands ###
